/* Inserta features */
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('1', 'Horario de contacto', '1', 'MLA1743-HORPREF', 'string');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('2', 'Color', '1', 'MLA1744-COLOREXT', 'list');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('3', 'Dirección', '1', 'MLA1744-DIREC', 'string');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('4', 'Unico dueño', '1', 'MLA1744-OWNER', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('5', 'Aire acondicionado', '1', 'MLA1744-AIRACON', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('6', 'Alarma de luces encendidas', '2', 'MLA1744-ALARMLUC', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('7', 'Apertura remota de baúl', '2', 'MLA1744-APERBAUL', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('8', 'Asientos eléctricos', '2', 'MLA1744-ASIENELEC', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('9', 'Asiento trasero rebatible', '2', 'MLA1744-ASREBAT-Y', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('10', 'Asiento conductor regulable en altura', '2', 'MLA1744-ASREGULA', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('11', 'Cierre centralizado de puertas', '2', 'MLA1744-BLQCNTDOOR', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('12', 'Climatizador automático', '2', 'MLA1744-CLIMAUT', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('13', 'Computadora de abordo', '2', 'MLA1744-COMPABO', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('14', 'Control de velocidad de crucero', '2', 'MLA1744-CTRLVEL', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('15', 'Espejos eléctricos', '2', 'MLA1744-ESPELEC', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('16', 'Sensor de estacionamiento', '2', 'MLA1744-ESTACIONAM', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('17', 'Faros regulables desde el interior', '2', 'MLA1744-FAROREG', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('18', 'GPS', '2', 'MLA1744-GPS', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('19', 'Sensor de lluvia', '2', 'MLA1744-SENSLL', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('20', 'Sensor de luz', '2', 'MLA1744-SENSLUZ', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('21', 'Tapizado de cuero', '2', 'MLA1744-TAPCUERO', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('22', 'Techo corredizo', '2', 'MLA1744-TECHOCORR', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('23', 'Cristales eléctricos', '2', 'MLA1744-VIDELEC', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('24', 'Limpia/lava luneta', '3', 'MLA1744-LIMPIA_LAV', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('25', 'Llantas de aleación', '3', 'MLA1744-LLANALEAC', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('26', 'Paragolpes pintados', '3', 'MLA1744-PARAGOLPES', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('27', 'Vidrios polarizados', '3', 'MLA1744-VIDPOLARIZ', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('28', 'Combustible', '4', 'MLA1744-COMBUS', 'list');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('29', 'Cant. de puertas', '4', 'MLA1744-DOOR', 'list');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('30', 'Kilómetros', '4', 'MLA1744-KMTS', 'string');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('31', 'Marca', '4', 'MLA1744-MARC', 'list');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('32', 'Modelo', '4', 'MLA1744-MODL', 'list');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('33', 'Transmisión', '4', 'MLA1744-TRANS', 'list');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('34', 'Año', '4', 'MLA1744-YEAR', 'list');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('35', 'Versión', '4', 'MLA92242-VERS', 'string');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('36', 'Tercer stop', '5', 'MLA1744-3LUZSTOP', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('37', 'Frenos ABS', '5', 'MLA1744-ABS', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('38', 'Airbag conductor', '5', 'MLA1744-AIR1', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('39', 'Airbag pasajero', '5', 'MLA1744-AIR2', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('40', 'Airbag laterales', '5', 'MLA1744-AIR3', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('41', 'Airbag de cortina', '5', 'MLA1744-AIRBAGCORT', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('42', 'Alarma', '5', 'MLA1744-ALAR', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('43', 'Apoya cabeza en asientos traseros', '5', 'MLA1744-APCABEZA', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('44', 'Blindado', '5', 'MLA1744-BLIND', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('45', 'Control de tracción', '5', 'MLA1744-CNTTRACC', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('46', 'Control de estabilidad', '5', 'MLA1744-CONTR', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('47', 'Doble tracción', '5', 'MLA1744-DOBTRACC-Y', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('48', 'Faros antinieblas delanteros', '5', 'MLA1744-FARANTI', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('49', 'Faros de xenón', '5', 'MLA1744-FAROXEN', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('50', 'Inmovilizador de motor', '5', 'MLA1744-INMOVMOT', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('51', 'Isofix', '5', 'MLA1744-ISOFIX', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('52', 'Faros antinieblas traseros', '5', 'MLA1744-NEBLTRAS', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('53', 'Repartidor electrónico de fuerza de frenado', '5', 'MLA1744-REPFUERZA', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('54', 'AM/FM', '6', 'MLA1744-AM_FM', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('55', 'Bluetooth', '6', 'MLA1744-BLUETOOTH', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('56', 'Caja de CD', '6', 'MLA1744-CAJACD', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('57', 'Cargador de CD', '6', 'MLA1744-CARGADORCD', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('58', 'Pasacassette', '6', 'MLA1744-CASET', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('59', 'Comando satelital de stereo', '6', 'MLA1744-COMANDOSAT', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('60', 'DVD', '6', 'MLA1744-DVD', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('61', 'Entrada auxiliar', '6', 'MLA1744-ENTAUXILIA', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('62', 'MP3', '6', 'MLA1744-MP3', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('63', 'CD', '6', 'MLA1744-REPRODCD', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('64', 'Tarjeta SD', '6', 'MLA1744-TARJETASD', 'boolean');
INSERT INTO `feature` (`id`, `name`, `GROUP_ID`, `MERCADO_LIBRE_ID`, `MERCADO_LIBRE_TYPE`) VALUES ('65', 'Entrada USB', '6', 'MLA1744-USB', 'boolean');
update feature set mercado_libre_type = 'BOOLEAN' where mercado_libre_type = 'boolean'
