




INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (1, 3, 0, 'ALFA ROMEO','2');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (2, 1, 0, 'ACURA','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (3, 5, 0, 'ASIA','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (4, 71, 1, 'ASIA','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (5, 63, 1, 'AGRALE','310');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (6, 6, 0, 'AUDI','5');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (7, 7, 0, 'AUTOBIANCHI','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (8, 60, 0, 'AUSTIN','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (9, 2, 0, 'ALEKO','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (10, 4, 0, 'ARO','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (11, 21, 1, 'AEOLUS','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (12, 58, 1, 'BLAC','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (13, 61, 1, 'BERTONE','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (14, 8, 0, 'BMW','9');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (15, 78, 1, 'BELAVTOMAZ','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (16, 62, 0, 'METRO','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (17, 11, 0, 'CITROEN','14');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (18, 13, 0, 'CHRYSLER','13');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (19, 12, 0, 'CHEVROLET','12');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (20, 72, 1, 'CHEVROLET','47');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (21, 108, 0, 'CHERY','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (22, 14, 1, 'DACIA','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (23, 112, 1, 'DFM','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (24, 15, 0, 'DAEWOO','16');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (25, 16, 0, 'DAIHATSU','222');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (26, 93, 1, 'DAIHATSU','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (27, 89, 1, 'DIMEX','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (28, 54, 0, 'ENIAK','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (29, 69, 1, 'F.E.R.E.S.A.','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (30, 18, 0, 'FORD','25');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (31, 73, 1, 'FORD','80');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (32, 51, 0, 'FERRARI','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (33, 17, 0, 'FIAT','24');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (34, 79, 1, 'G.A.Z.','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (35, 64, 1, 'GROSSPAL','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (36, 19, 0, 'HONDA','28');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (37, 52, 0, 'HAM-JIANG','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (38, 20, 0, 'HYUNDAI','30');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (39, 80, 1, 'HINO','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (40, 99, 0, 'HEIBAO','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (41, 49, 0, 'HUMMER','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (42, 81, 0, 'IZH','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (43, 87, 1, 'INTERNATIONAL','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (44, 41, 1, 'IVECO','134');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (45, 22, 0, 'ISUZU','79');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (46, 98, 1, 'JAC','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (47, 113, 1, 'JMC','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (48, 68, 1, 'JINBEI','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (49, 23, 0, 'JAGUAR','33');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (50, 24, 0, 'KIA','35');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (51, 74, 1, 'KIA','147');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (52, 83, 1, 'KENWORTH','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (53, 82, 1, 'KAMAZ','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (54, 25, 0, 'LADA','80');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (55, 53, 0, 'LANCIA','379');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (56, 114, 1, 'LIFAN','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (57, 84, 1, 'LIAZ','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (58, 26, 0, 'MAZDA','43');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (59, 90, 1, 'MAZDA','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (60, 55, 0, 'MAHINDRA','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (61, 29, 0, 'MITSUBISH','48');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (105, 91, 1, 'MITSUBISHI','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (62, 102, 0, 'MASERATI','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (63, 106, 0, 'MINI COOPER','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (64, 111, 1, 'MACK','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (65, 67, 0, 'MAESTRO','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (66, 28, 0, 'MERCEDES BENZ','44');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (67, 75, 1, 'MERCEDES BENZ','191');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (68, 77, 0, 'NAKAI','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (69, 30, 0, 'NISSAN','50');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (70, 92, 1, 'NISSAN','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (71, 31, 0, 'OPEL','380');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (72, 35, 0, 'PORSCHE','57');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (73, 48, 0, 'PROTON','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (74, 94, 0, 'PIAGGIO','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (75, 32, 0, 'PEUGEOT','54');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (76, 33, 0, 'POLONEZ','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (77, 37, 0, 'LAND ROVER','38');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (78, 65, 1, 'RANQUEL','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (79, 56, 0, 'RASTROJERO','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (80, 107, 0, 'ROLLS ROYCE','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (81, 36, 0, 'RENAULT','58');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (82, 70, 1, 'RENAULT','238');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (83, 50, 1, 'SCANIA','245');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (84, 103, 0, 'SANTANA','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (85, 40, 0, 'SCODA','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (86, 38, 0, 'SAAB','381');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (87, 95, 1, 'SANXING','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (88, 43, 0, 'SUZUKI','66');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (89, 101, 1, 'SPACE','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (90, 96, 1, 'STAR','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (91, 39, 0, 'SEAT','86');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (92, 110, 0, 'SMART','88');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (93, 42, 0, 'SUBARU','65');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (94, 45, 0, 'TOYOTA','67');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (95, 44, 0, 'TAVRIA','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (96, 57, 0, 'TATA','377');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (106, 76, 1, 'TATA','302');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (97, 85, 0, 'UAZ','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (98, 47, 0, 'VOLVO','70');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (99, 88, 1, 'VOLVO','285');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (100, 46, 0, 'VOLKSWAGEN','69');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (101, 66, 1, 'VOLKSWAGEN','286');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (102, 100, 0, 'WULING','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (103, 97, 0, 'YANTAI','93');
INSERT INTO MAKES (ID, INFOAUTO_MAKE, VEHICLE_TYPE, NAME, OLX_ID)
VALUES (104, 86, 1, 'YUEJIN','302');


























