CREATE TABLE `CONSIGNMENTS` (
  `DEAL_PRICE` int(11) NOT NULL,
  `VEHICLE_OPERATION_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`VEHICLE_OPERATION_ID`),
  KEY `FK4B29BFF6B180CD5A` (`VEHICLE_OPERATION_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;