CREATE TABLE `DEALERSHIPS_VEHICLES` (
  `DEALERSHIPS_ID` bigint(20) NOT NULL,
  `VEHICLES_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`DEALERSHIPS_ID`,`VEHICLES_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;