
CREATE TABLE `EXPENSES` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` datetime DEFAULT NULL,
  `UPDATED_TIME` datetime DEFAULT NULL,
  `NAME` varchar(255) NOT NULL,
  `COST` bigint(20) NOT NULL,
  `PAID` bit(1) NOT NULL, 
  `SALE_ITEM_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;