CREATE TABLE `FEATURE_VALUE` (
  `id` bigint(20) NOT NULL,
   `CREATED_AT` datetime DEFAULT NULL,
  `UPDATED_TIME` datetime DEFAULT NULL,
  `VALUE` varchar(255) DEFAULT NULL,
  `FEATURE_ID` bigint(20) NOT NULL,
  `MERCADO_LIBRE_ID` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;