CREATE TABLE `FEATURE` (
  `id` bigint(20) NOT NULL,
  `CREATED_AT` datetime DEFAULT NULL,
  `UPDATED_TIME` datetime DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `GROUP_ID` bigint(20) NOT NULL,
  `MERCADO_LIBRE_ID` varchar(255) DEFAULT NULL,
  `MERCADO_LIBRE_TYPE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;