CREATE TABLE `IMAGE_URLS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VEHICLE_ID` bigint(20) NOT NULL,
  `IMAGE_URL` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=8 DEFAULT CHARSET=latin1;