CREATE TABLE `LOCATION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` datetime DEFAULT NULL,
  `UPDATED_TIME` datetime DEFAULT NULL,
  `ADDRESS_LINE` varchar(255) DEFAULT NULL,
  `ZIP_CODE` varchar(255) DEFAULT NULL,
  `COUNTRY_ID` bigint(20) NOT NULL,
  `STATE_ID` bigint(20) NOT NULL,
  `CITY_ID` bigint(20) NOT NULL,
  `NEIGHBORHOOD_ID` bigint(20) NOT NULL,
  `LATITUDE` varchar(255) DEFAULT NULL,
  `LONGITUDE` varchar(255) DEFAULT NULL,
  `OPEN_HOURS` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;