CREATE TABLE `MAKES` (
 `ID` int(11) NOT NULL,
 `CREATED_AT` datetime DEFAULT NULL,
 `UPDATED_TIME` datetime DEFAULT NULL,
 `INFOAUTO_MAKE` int(11) DEFAULT NULL,
 `VEHICLE_TYPE` int(11) NOT NULL,
 `NAME` varchar(255) DEFAULT NULL,
 `OLX_ID` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;