




INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (3, 0, 'ALFA ROMEO');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (1, 0, 'ACURA');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (5, 0, 'ASIA');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (71, 1, 'ASIA');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (63, 1, 'AGRALE');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (6, 0, 'AUDI');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (7, 0, 'AUTOBIANCHI');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (60, 0, 'AUSTIN');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (2, 0, 'ALEKO');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (4, 0, 'ARO');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (21, 1, 'AEOLUS');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (58, 1, 'BLAC');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (61, 1, 'BERTONE');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (8, 0, 'BMW');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (78, 1, 'BELAVTOMAZ');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (62, 0, 'METRO');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (11, 0, 'CITROEN');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (13, 0, 'CHRYSLER');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (12, 0, 'CHEVROLET');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (72, 1, 'CHEVROLET');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (108, 0, 'CHERY');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (14, 1, 'DACIA');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (112, 1, 'DFM');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (15, 0, 'DAEWOO');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (16, 0, 'DAIHATSU');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (93, 1, 'DAIHATSU');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (89, 1, 'DIMEX');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (54, 0, 'ENIAK');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (69, 1, 'F.E.R.E.S.A.');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (18, 0, 'FORD');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (73, 1, 'FORD');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (51, 0, 'FERRARI');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (17, 0, 'FIAT');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (79, 1, 'G.A.Z.');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (64, 1, 'GROSSPAL');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (19, 0, 'HONDA');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (52, 0, 'HAM-JIANG');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (20, 0, 'HYUNDAI');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (80, 1, 'HINO');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (99, 0, 'HEIBAO');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (49, 0, 'HUMMER');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (81, 0, 'IZH');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (87, 1, 'INTERNATIONAL');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (41, 1, 'IVECO');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (22, 0, 'ISUZU');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (98, 1, 'JAC');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (113, 1, 'JMC');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (68, 1, 'JINBEI');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (23, 0, 'JAGUAR');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (24, 0, 'KIA');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (74, 1, 'KIA');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (83, 1, 'KENWORTH');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (82, 1, 'KAMAZ');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (25, 0, 'LADA');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (53, 0, 'LANCIA');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (114, 1, 'LIFAN');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (84, 1, 'LIAZ');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (26, 0, 'MAZDA');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (90, 1, 'MAZDA');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (55, 0, 'MAHINDRA');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (29, 0, 'MITSUBISH');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (91, 1, 'MITSUBISHI');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (102, 0, 'MASERATI');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (106, 0, 'MINI COOPER');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (111, 1, 'MACK');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (67, 0, 'MAESTRO');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (28, 0, 'MERCEDES BENZ');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (75, 1, 'MERCEDES BENZ');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (77, 0, 'NAKAI');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (30, 0, 'NISSAN');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (92, 1, 'NISSAN');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (31, 0, 'OPEL');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (35, 0, 'PORSCHE');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (48, 0, 'PROTON');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (94, 0, 'PIAGGIO');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (32, 0, 'PEUGEOT');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (33, 0, 'POLONEZ');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (37, 0, 'LAND ROVER');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (65, 1, 'RANQUEL');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (56, 0, 'RASTROJERO');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (107, 0, 'ROLLS ROYCE');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (36, 0, 'RENAULT');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (70, 1, 'RENAULT');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (50, 1, 'SCANIA');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (103, 0, 'SANTANA');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (40, 0, 'SCODA');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (38, 0, 'SAAB');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (95, 1, 'SANXING');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (43, 0, 'SUZUKI');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (101, 1, 'SPACE');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (96, 1, 'STAR');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (39, 0, 'SEAT');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (110, 0, 'SMART');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (42, 0, 'SUBARU');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (45, 0, 'TOYOTA');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (44, 0, 'TAVRIA');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (57, 0, 'TATA');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (76, 1, 'TATA');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (85, 0, 'UAZ');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (47, 0, 'VOLVO');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (88, 1, 'VOLVO');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (46, 0, 'VOLKSWAGEN');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (66, 1, 'VOLKSWAGEN');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (100, 0, 'WULING');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (97, 0, 'YANTAI');
INSERT INTO MAKES (INFOAUTO_MAKE, VEHICLE_TYPE, NAME)
VALUES (86, 1, 'YUEJIN');


























