CREATE TABLE `MAKES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `INFOAUTO_MAKE` int(11) DEFAULT NULL,
  `VEHICLE_TYPE` int(11) NOT NULL,
  `NAME` varchar(255) DEFAULT NULL,

  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;