CREATE TABLE `MODELS` (
	  `ID` int(11) NOT NULL AUTO_INCREMENT,
	  `MAKE_ID` int(11) NOT NULL,
	  `COD_INFOAUTO` int(11) NOT NULL,
	  `NAME` varchar(255) DEFAULT NULL,
	  PRIMARY KEY (`ID`)
	) ENGINE=MyISAM DEFAULT CHARSET=latin1;