CREATE TABLE `PURCHASES` (
  `PAID_AMOUNT` int(11) NOT NULL,
  `PAYMENT_TYPE` varchar(255) DEFAULT NULL,
  `VEHICLE_OPERATION_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`VEHICLE_OPERATION_ID`),
  KEY `FK3B4FAB72B180CD5A` (`VEHICLE_OPERATION_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;