CREATE TABLE `RESERVATIONS` (
  `ADVANCE_PAYMENT` bigint(20) NOT NULL,
  `DAYS_ON_HOLD` int(11) NOT NULL,
  `VEHICLE_OPERATION_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`VEHICLE_OPERATION_ID`),
  KEY `FK41F21E27B180CD5A` (`VEHICLE_OPERATION_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;