CREATE TABLE `USER_ROLES` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ACCOUNTS_ID` bigint(20) NOT NULL,
  `ROLE` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;