CREATE TABLE `VEHICLE_FEATURE_VALUE` (
  `VEHICLE_ID` bigint(20) NOT NULL,
  `FEATURE_VALUE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`VEHICLE_ID`,`FEATURE_VALUE_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;